namespace EnchantmentPack.Enums
{
    public enum EEnchantmentName
    {
        None,
        BetterExp,
        PassiveHeal,
        StunDoubleDamage,
        BleedStacking,
        PoisonCanStack,
        DashKill,
        PoisonShare,
        ExplodingDash,
        BetterBooks,
        ExplosiveBullets,
        FireHeal,
        HealingOrb,
        Revive,
        Sharpness,
        HealField,
        LongerBurn,
        LongerStun,
        LongerPoison,
        StunSlowed,
        Rage,
        Luck,
        AdditionalDash,
        AdditionalDash1,
        AdditionalDash2,
        BetterHeal,
        BetterHeal1,
        BetterHeal2,
        Speed,
        Speed1,
        Speed2
    }
}